from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
DRAFT = ROOT / "草稿.md"
OUTPUT = ROOT / "index.html"
text = DRAFT.read_text(encoding="utf-8")

daily = [(d, int(v.replace(",", ""))) for d, v in re.findall(r"\|(20\d\d-\d\d-\d\d)\|([\d,]+)\|", text)]

message_types = [
    ("文字", 314441, 72.81, "#3559E0"),
    ("图片", 59297, 13.73, "#E0783A"),
    ("表情包", 32354, 7.49, "#48A078"),
    ("其他", 25204, 5.84, "#8B95A7"),
    ("视频", 564, 0.13, "#9B66C2"),
]
keywords = [("恩师", 6066), ("荣光", 3059), ("不赖", 2897), ("群友", 2892), ("塔罗牌", 2501), ("waifu", 2484), ("同济", 2441), ("jrrp", 2347), ("老婆", 2337), ("人品", 2254)]
messages = [("？", 5109), ("塔罗牌", 2432), ("waifu", 2290), ("jrrp", 2171), ("jrys", 1507), ("zanwo", 1211), ("何意味", 940), ("不赖", 882), ("（）", 672), ("😭", 632)]
emojis = [("🥟", 5898), ("😭", 3569), ("🌧", 3367), ("😡", 1966), ("😋", 1468), ("🐔", 1231), ("😰", 1187), ("👻", 1082), ("🤔", 1057), ("👀", 917)]
speakers = [
    ("Niddle Doracid", "3927950051", 25528), ("锦依卫gm", "1048118662", 25029),
    ("Cinty", "3232896164", 18157), ("焱焱", "2652856799", 15592),
    ("大大怪", "3277961484", 14782), ("积气人", "3874402736", 13594),
    ("Gunpowder", "1213956808", 13408), ("2267601010", "2267601010", 12860),
    ("s7", "50891508", 9661), ("哲三Tetsumi", "123199422", 9418),
]
days = [("Gunpowder", 353), ("Niddle Doracid", 351), ("Cinty", 343), ("。", 338), ("2267601010", 338), ("锦依卫gm", 328), ("水中虬", 318), ("雪墨达峻", 311), ("焱焱", 307), ("UmbrellaSoldier", 305)]

payload = json.dumps({"daily": daily, "types": message_types, "keywords": keywords, "messages": messages, "emojis": emojis, "speakers": speakers, "days": days}, ensure_ascii=False)

html = r'''<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>25级国豪学生群年度报告</title>
<style>
:root{--bg:#f4f6fb;--paper:#fff;--ink:#162033;--sub:#667085;--line:#e5e9f2;--blue:#3559e0;--orange:#e0783a;--green:#48a078;--purple:#9b66c2;--gray:#8b95a7}
*{box-sizing:border-box}html{background:#dfe4ed}body{margin:0;color:var(--ink);font-family:"Microsoft YaHei UI","PingFang SC","Noto Sans CJK SC",Arial,sans-serif;background:var(--bg)}
.poster{width:min(1080px,100%);margin:auto;overflow:hidden;background:var(--bg)}
.hero{min-height:720px;padding:92px 78px 72px;background:#172554;color:#fff;position:relative;display:flex;flex-direction:column;justify-content:space-between}
.hero:after{content:"";position:absolute;width:460px;height:460px;border:100px solid rgba(255,255,255,.06);border-radius:50%;right:-180px;bottom:-210px}.eyebrow,.section-no{font-size:15px;font-weight:800;letter-spacing:.18em;text-transform:uppercase}.hero h1{margin:18px 0 8px;font-size:78px;line-height:1.08;letter-spacing:-.05em;max-width:760px}.hero h1 span{color:#b9c6ff}.hero-sub{font-size:28px;color:#d8def5}.hero-bottom{display:flex;justify-content:space-between;align-items:flex-end}.hero-date{font-size:20px;color:#bac4e2}.hero-count strong{display:block;font-size:68px;line-height:1}.hero-count span{color:#bac4e2}
section{padding:72px 64px 0}.section-head{display:flex;align-items:end;justify-content:space-between;margin-bottom:30px}.section-title{margin:8px 0 0;font-size:42px;letter-spacing:-.04em}.section-note{color:var(--sub);font-size:17px}.card{background:var(--paper);border:1px solid var(--line);border-radius:28px;padding:34px;box-shadow:0 12px 36px rgba(29,45,82,.045)}
.overview{display:grid;grid-template-columns:1fr 1.25fr;gap:20px}.donut-wrap{display:flex;align-items:center;justify-content:center;min-height:360px}.donut{width:270px;height:270px;border-radius:50%;position:relative}.donut:after{content:"";position:absolute;inset:48px;background:white;border-radius:50%}.donut-label{position:absolute;z-index:2;inset:0;display:flex;flex-direction:column;justify-content:center;text-align:center}.donut-label strong{font-size:42px}.donut-label span{font-size:15px;color:var(--sub)}.legend{display:grid;gap:0}.legend-row{display:grid;grid-template-columns:16px 1fr auto;align-items:center;gap:14px;padding:16px 0;border-bottom:1px solid var(--line)}.legend-row:last-child{border:0}.swatch{width:12px;height:12px;border-radius:4px}.legend-name{font-size:19px;font-weight:700}.legend-val{text-align:right}.legend-val strong{font-size:20px}.legend-val small{display:block;color:var(--sub);margin-top:3px}
.kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:20px}.kpi{padding:28px}.kpi span{display:block;color:var(--sub);margin-bottom:10px}.kpi strong{font-size:34px}.kpi em{display:block;margin-top:8px;color:var(--sub);font-style:normal}
.chart-card{position:relative;padding:34px 22px 24px}.chart-title{padding:0 12px}.chart-title h3{font-size:25px;margin:0 0 6px}.chart-title p{color:var(--sub);margin:0}.line-chart{width:100%;height:360px;display:block;overflow:visible;margin-top:18px}.grid{stroke:#e8ebf2;stroke-width:1}.axis-label{fill:#7b8496;font-size:12px}.area{fill:url(#areaGradient)}.series-line{fill:none;stroke:var(--blue);stroke-width:3;stroke-linejoin:round;stroke-linecap:round}.peak-dot{fill:white;stroke:var(--orange);stroke-width:4}.low-dot{fill:white;stroke:var(--green);stroke-width:4}.annotation{fill:var(--ink);font-size:13px;font-weight:700}.chart-hit{fill:transparent;cursor:crosshair}.crosshair{stroke:#97a1b4;stroke-dasharray:4 4;display:none}.hover-dot{fill:#fff;stroke:var(--blue);stroke-width:3;display:none}.tooltip{position:absolute;display:none;background:#172033;color:#fff;padding:9px 12px;border-radius:10px;font-size:13px;pointer-events:none;white-space:nowrap;z-index:5}
.two-col{display:grid;grid-template-columns:1.18fr .82fr;gap:20px}.rank-bars{display:grid;gap:14px}.bar-row{display:grid;grid-template-columns:34px 92px 1fr 58px;align-items:center;gap:10px}.rank{color:var(--sub);font-weight:800}.bar-name{font-size:17px;font-weight:700}.track{height:12px;background:#eef1f7;border-radius:6px;overflow:hidden}.fill{height:100%;background:var(--blue);border-radius:0 6px 6px 0}.bar-value{text-align:right;font-variant-numeric:tabular-nums;font-weight:700}.compact-list{display:grid;grid-template-columns:1fr 1fr;gap:8px 20px}.compact-item{display:flex;align-items:center;justify-content:space-between;padding:13px 0;border-bottom:1px solid var(--line)}.compact-item span:first-child{font-weight:800}.compact-item small{color:var(--sub)}
.emoji-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.emoji{padding:22px 10px;text-align:center;border:1px solid var(--line);border-radius:20px;background:#fbfcfe}.emoji-char{font-family:"Segoe UI Emoji","Apple Color Emoji",sans-serif;font-size:44px;line-height:1.2}.emoji strong{display:block;margin-top:9px;font-size:17px}.emoji small{color:var(--sub)}
.people-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}.person{padding:22px 10px;text-align:center;border:1px solid var(--line);border-radius:22px;background:#fff;min-width:0}.avatar{width:86px;height:86px;margin:auto;border-radius:50%;display:grid;place-items:center;color:#fff;font-size:28px;font-weight:900;position:relative;overflow:hidden}.avatar img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.person-name{font-size:15px;font-weight:800;margin:13px 0 5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.person-value{font-size:20px;color:var(--blue);font-weight:900}.person small{color:var(--sub)}.day-list{display:grid;grid-template-columns:1fr 1fr;gap:0 28px}.day-row{display:grid;grid-template-columns:30px 1fr auto;gap:8px;padding:14px 0;border-bottom:1px solid var(--line);align-items:center}.day-row b{color:var(--sub)}.day-row strong{font-size:18px}
.footer{margin-top:76px;padding:72px 64px 82px;background:#172554;color:#fff}.footer-grid{display:grid;grid-template-columns:1fr 260px;gap:50px;align-items:center}.footer h2{font-size:42px;line-height:1.3;margin:0 0 18px}.footer p{color:#c8d1ec;font-size:18px;line-height:1.8}.qr{width:240px;height:240px;border:2px dashed rgba(255,255,255,.35);border-radius:24px;display:grid;place-items:center;text-align:center;color:#c8d1ec;background:rgba(255,255,255,.05);padding:25px}.qr img{width:100%;height:100%;object-fit:contain}.brandline{margin-top:50px;padding-top:28px;border-top:1px solid rgba(255,255,255,.15);display:flex;justify-content:space-between;color:#9eabd0}
@media(max-width:760px){.hero{padding:62px 30px;min-height:600px}.hero h1{font-size:50px}.hero-sub{font-size:21px}.hero-count strong{font-size:42px}section{padding:52px 22px 0}.overview,.two-col,.footer-grid{grid-template-columns:1fr}.section-head{display:block}.section-note{margin-top:8px}.kpis{grid-template-columns:1fr}.people-grid{grid-template-columns:repeat(2,1fr)}.emoji-grid{grid-template-columns:repeat(2,1fr)}.footer{padding:58px 24px}.qr{margin:auto}.bar-row{grid-template-columns:25px 76px 1fr 48px}.compact-list,.day-list{grid-template-columns:1fr}.hero-bottom{gap:20px}.section-title{font-size:34px}}
@media print{html{background:#fff}.poster{width:1080px}.tooltip{display:none!important}}
</style>
</head>
<body><main class="poster">
<header class="hero"><div><div class="eyebrow">2025 — 2026 · Group Annual Review</div><h1>「复交得不到的<span>人才</span>」</h1><div class="hero-sub">25级国豪学生群年度报告</div></div><div class="hero-bottom"><div class="hero-date">2025.07.27 — 2026.07.26<br>我们一起聊过的这一年</div><div class="hero-count"><strong>431,860</strong><span>条消息，组成共同记忆</span></div></div></header>
<section><div class="section-head"><div><div class="section-no">01 · OVERVIEW</div><h2 class="section-title">这一年，我们说了很多</h2></div><div class="section-note">平均每天约 1,183 条消息</div></div><div class="overview"><div class="card donut-wrap"><div class="donut" id="donut"><div class="donut-label"><strong>431,860</strong><span>年度消息总量</span></div></div></div><div class="card legend" id="legend"></div></div><div class="kpis"><div class="card kpi"><span>最热闹的一天</span><strong>4,831 条</strong><em>2025 年 9 月 10 日</em></div><div class="card kpi"><span>最安静的一天</span><strong>26 条</strong><em>2026 年 2 月 6 日</em></div><div class="card kpi"><span>覆盖时长</span><strong>365 天</strong><em>从盛夏聊到下一个盛夏</em></div></div></section>
<section><div class="section-head"><div><div class="section-no">02 · RHYTHM</div><h2 class="section-title">群聊有自己的潮汐</h2></div><div class="section-note">入学季最热闹，寒假最安静</div></div><div class="card chart-card"><div class="chart-title"><h3>每日消息数变化</h3><p>按月观察全年节奏 · 悬停可查看每日数据</p></div><div class="tooltip" id="tooltip"></div><svg id="lineChart" class="line-chart" role="img" aria-label="2025年7月至2026年7月每日消息数折线图"></svg></div></section>
<section><div class="section-head"><div><div class="section-no">03 · WORDS</div><h2 class="section-title">属于我们的年度黑话</h2></div><div class="section-note">“恩师”以 6,066 次断层领先</div></div><div class="two-col"><div class="card"><h3>年度热词 TOP 10</h3><div class="rank-bars" id="keywordBars"></div></div><div class="card"><h3>最常发送的文字</h3><div class="compact-list" id="messageList"></div></div></div></section>
<section><div class="section-head"><div><div class="section-no">04 · EMOJI</div><h2 class="section-title">有些情绪，一个表情就够了</h2></div><div class="section-note">🥟 是当之无愧的年度表情</div></div><div class="card"><div class="emoji-grid" id="emojiGrid"></div></div></section>
<section><div class="section-head"><div><div class="section-no">05 · PEOPLE</div><h2 class="section-title">谢谢一直在线的你们</h2></div><div class="section-note">头像暂用昵称首字占位，可随时替换</div></div><div class="card"><h3>发言最多的群友 TOP 10</h3><div class="people-grid" id="peopleGrid"></div></div><div class="card" style="margin-top:20px"><h3>全年在线天数 TOP 10</h3><div class="day-list" id="dayList"></div></div></section>
<footer class="footer"><div class="footer-grid"><div><div class="section-no">TO BE CONTINUED</div><h2>谢谢大家，让这个群热闹了一整年。</h2><p>新的一年，愿我们继续抒写国豪的故事。<br>如果觉得现在的群名该换换了，欢迎扫码留下你的创意。</p></div><div class="qr" id="qr"><div><b>调查二维码待补充</b><br><small>放入 assets/survey-qr.png<br>即可自动显示</small></div></div></div><div class="brandline"><span>25级国豪学生群</span><span>Annual Review · 2026</span></div></footer>
</main>
<script>
const DATA = __DATA__;
const nf = new Intl.NumberFormat('zh-CN');
const donutStops=[];let cursor=0;DATA.types.forEach(([name,value,pct,color])=>{donutStops.push(`${color} ${cursor}% ${cursor+pct}%`);cursor+=pct});document.querySelector('#donut').style.background=`conic-gradient(${donutStops.join(',')})`;
document.querySelector('#legend').innerHTML=DATA.types.map(([n,v,p,c])=>`<div class="legend-row"><i class="swatch" style="background:${c}"></i><div class="legend-name">${n}</div><div class="legend-val"><strong>${nf.format(v)}</strong><small>${p.toFixed(2)}%</small></div></div>`).join('');
const maxKw=Math.max(...DATA.keywords.map(x=>x[1]));document.querySelector('#keywordBars').innerHTML=DATA.keywords.map(([n,v],i)=>`<div class="bar-row"><span class="rank">${String(i+1).padStart(2,'0')}</span><span class="bar-name">${n}</span><div class="track"><div class="fill" style="width:${v/maxKw*100}%;${i===0?'background:var(--orange)':''}"></div></div><span class="bar-value">${nf.format(v)}</span></div>`).join('');
document.querySelector('#messageList').innerHTML=DATA.messages.map(([n,v],i)=>`<div class="compact-item"><span>${i+1}. ${n}</span><small>${nf.format(v)} 次</small></div>`).join('');
document.querySelector('#emojiGrid').innerHTML=DATA.emojis.map(([e,v],i)=>`<div class="emoji"><div class="emoji-char">${e}</div><strong>${nf.format(v)}</strong><small>年度第 ${i+1} 名</small></div>`).join('');
const avatarColors=['#3559e0','#e0783a','#48a078','#9b66c2','#52607a','#c05b75','#3c7d90','#7867bb','#a56f35','#3d7a63'];const initials=n=>/^\d+$/.test(n)?n.slice(-2):(n.match(/[A-Za-z]/)?.[0]||n[0]||'友').toUpperCase();
document.querySelector('#peopleGrid').innerHTML=DATA.speakers.map(([n,q,v],i)=>`<div class="person"><div class="avatar" style="background:${avatarColors[i]}"><span>${initials(n)}</span><img src="assets/avatars/${q}.jpg" alt="" onerror="this.remove()"></div><div class="person-name" title="${n}">${n}</div><div class="person-value">${nf.format(v)}</div><small>条消息 · #${i+1}</small></div>`).join('');
document.querySelector('#dayList').innerHTML=DATA.days.map(([n,v],i)=>`<div class="day-row"><b>${i+1}</b><span>${n}</span><strong>${v} 天</strong></div>`).join('');
const qrImg=new Image();qrImg.src='assets/survey-qr.png';qrImg.onload=()=>document.querySelector('#qr').innerHTML='<img src="assets/survey-qr.png" alt="群名创意调查二维码">';
function drawChart(){const svg=document.querySelector('#lineChart'),box=svg.getBoundingClientRect(),W=Math.max(600,box.width),H=360,m={l:54,r:22,t:25,b:42},pw=W-m.l-m.r,ph=H-m.t-m.b,max=5000;svg.setAttribute('viewBox',`0 0 ${W} ${H}`);const x=i=>m.l+i/(DATA.daily.length-1)*pw,y=v=>m.t+(1-v/max)*ph;const pts=DATA.daily.map((d,i)=>[x(i),y(d[1])]);const line=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+','+p[1].toFixed(1)).join(' ');const area=`M${m.l},${m.t+ph} `+pts.map((p,i)=>(i?'L':'L')+p[0].toFixed(1)+','+p[1].toFixed(1)).join(' ')+` L${m.l+pw},${m.t+ph} Z`;let s='<defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#3559e0" stop-opacity=".24"/><stop offset="1" stop-color="#3559e0" stop-opacity=".02"/></linearGradient></defs>';[0,1000,2000,3000,4000,5000].forEach(v=>{s+=`<line class="grid" x1="${m.l}" x2="${m.l+pw}" y1="${y(v)}" y2="${y(v)}"/><text class="axis-label" x="${m.l-10}" y="${y(v)+4}" text-anchor="end">${v===0?'0':v/1000+'k'}</text>`});const monthIdx=[];DATA.daily.forEach((d,i)=>{if(d[0].endsWith('-01')||i===0)monthIdx.push(i)});monthIdx.forEach(i=>s+=`<text class="axis-label" x="${x(i)}" y="${H-12}" text-anchor="middle">${DATA.daily[i][0].slice(2,7).replace('-','.')}</text>`);s+=`<path class="area" d="${area}"/><path class="series-line" d="${line}"/>`;const hi=DATA.daily.findIndex(d=>d[1]===4831),lo=DATA.daily.findIndex(d=>d[1]===26);s+=`<circle class="peak-dot" cx="${x(hi)}" cy="${y(4831)}" r="6"/><text class="annotation" x="${x(hi)-8}" y="${y(4831)-14}" text-anchor="end">峰值 4,831</text><circle class="low-dot" cx="${x(lo)}" cy="${y(26)}" r="6"/><text class="annotation" x="${x(lo)+8}" y="${y(26)-12}">低谷 26</text><line id="crosshair" class="crosshair" y1="${m.t}" y2="${m.t+ph}"/><circle id="hoverDot" class="hover-dot" r="5"/><rect class="chart-hit" x="${m.l}" y="${m.t}" width="${pw}" height="${ph}"/>`;svg.innerHTML=s;const hit=svg.querySelector('.chart-hit'),tip=document.querySelector('#tooltip'),cross=svg.querySelector('#crosshair'),dot=svg.querySelector('#hoverDot');hit.addEventListener('pointermove',e=>{const r=svg.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*W,idx=Math.max(0,Math.min(DATA.daily.length-1,Math.round((px-m.l)/pw*(DATA.daily.length-1)))),d=DATA.daily[idx],cx=x(idx),cy=y(d[1]);cross.style.display=dot.style.display='block';cross.setAttribute('x1',cx);cross.setAttribute('x2',cx);dot.setAttribute('cx',cx);dot.setAttribute('cy',cy);tip.style.display='block';tip.textContent=`${d[0]} · ${nf.format(d[1])} 条`;tip.style.left=Math.min(box.width-145,e.clientX-r.left+10)+'px';tip.style.top=Math.max(20,e.clientY-r.top-44)+'px'});hit.addEventListener('pointerleave',()=>{tip.style.display=cross.style.display=dot.style.display='none'})}
drawChart();addEventListener('resize',drawChart);
</script></body></html>'''.replace('__DATA__', payload)
OUTPUT.write_text(html, encoding='utf-8')
print(f"Wrote {OUTPUT} with {len(daily)} daily records")
